<?php

namespace CandidaturesBundle\Repository;

/**
 * CandidaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidaturesRepository extends \Doctrine\ORM\EntityRepository
{
}
