services:
  # Surcharge du formulaire d'inscription
  ocuserbudle.form.registration:
      class: OCUserBundle\Form\Type\RegistrationFormType
      tags:
          - { name: form.type, alias: app_user_registration }