<?php

namespace OCUserBundle\Repository;

/**
 * ChomeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChomeurRepository extends \Doctrine\ORM\EntityRepository
{
}
