<?php

namespace OCUserBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retourne l'entreprise lié a l'user
     * @param $user
     * @return mixed
     */
    public function getEntreprise($user)
    {
        return $this->findBy(
            array(
                'user'=>$user,
            )
        )[0];
    }
}
