<?php

namespace QcmBundle\Repository;
use Symfony\Component\Console\Question\Question;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Retourne la question numero $page du questionnaire
     * @param $questionnaires
     * @param $numero
     * @return Question | False
     */
    public function getQuestion($questionnaires,$numero){

        $listeQuestions = $this->findBy(
            array(
                'idQuestionnaire'=>$questionnaires,
            ),
            array(
                'id' => 'ASC'
            )
        );

        // Si le listequestion n'est pas vide, et que la question demandée existe
        if((bool) $listeQuestions && isset($listeQuestions[$numero])) {
            return $listeQuestions[$numero];
        } else {
            return false;
        }
    }
}
